In [1]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.layers import Dense, Conv1D, Flatten
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
iris = load_iris()
x = iris['data']
y = iris['target']

train_x, test_x, train_y, test_y = train_test_split(x, y, stratify=y, test_size=0.2, random_state=30)

train_x = np.reshape(train_x, (len(train_x), 4, 1))
test_x = np.reshape(test_x, (len(test_x), 4, 1))

In [3]:
model = keras.Sequential()
model.add(Conv1D(4, 3, activation='relu', input_shape=(4,1)))
model.add(Flatten())
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation="softmax"))

model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 2, 4)              16        
_________________________________________________________________
flatten (Flatten)            (None, 8)                 0         
_________________________________________________________________
dense (Dense)                (None, 10)                90        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 249
Trainable params: 249
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)
loss, acc = model.evaluate(test_x, test_y)
result = model.predict(test_x)

30/30 [==============================] - 0s 3ms/sample - loss: 0.1480 - accuracy: 0.9333


In [5]:
print(result)
print(np.argmax(result, axis=1))

[[2.5273684e-08 2.3925351e-01 7.6074642e-01]
 [3.0837924e-08 3.1035900e-02 9.6896410e-01]
 [9.9957591e-01 4.2406985e-04 1.1159365e-24]
 [7.6944572e-03 9.9230558e-01 9.5735349e-09]
 [4.4592008e-02 9.5540798e-01 1.0437524e-09]
 [9.9899071e-01 1.0093240e-03 3.7054347e-22]
 [9.9891615e-01 1.0838690e-03 5.6770848e-22]
 [9.9877006e-01 1.2299411e-03 1.2466563e-21]
 [6.4491260e-08 3.7271029e-01 6.2728965e-01]
 [6.1891791e-05 9.9990714e-01 3.1003692e-05]
 [9.9022768e-04 9.9900693e-01 2.8988436e-06]
 [2.3611217e-09 1.2179002e-02 9.8782104e-01]
 [9.3554595e-04 9.9906319e-01 1.2924633e-06]
 [1.5833559e-10 2.9113062e-03 9.9708873e-01]
 [9.9928844e-01 7.1148376e-04 3.1026155e-23]
 [9.9866247e-01 1.3374959e-03 2.1724043e-21]
 [9.9823749e-01 1.7624928e-03 3.3195717e-21]
 [3.5687287e-06 9.7078133e-01 2.9215043e-02]
 [9.9933857e-01 6.6137873e-04 1.9022362e-23]
 [3.2723314e-05 9.9898046e-01 9.8673382e-04]
 [4.0775032e-07 7.7942896e-01 2.2057068e-01]
 [9.9815696e-01 1.8429864e-03 1.1637866e-20]
 [3.015174